W#include<iostream>
using namespace std;
int main(){
	cout<<"                    Part A "<<endl;
	cout<<"-------------------------------------------------"<<endl;
	const int size = 15;
	int arr[size] = {10, 5, 15, 20, 45, 2, 3, 1, 6, 33, 45, 88, 55 ,50, 51};
	cout<<arr[0]<<" ";
	cout<<arr[1]<<" ";
	cout<<arr[2]<<" ";
	cout<<arr[3]<<" ";
	cout<<arr[4]<<" ";
	cout<<arr[5]<<" ";
	cout<<arr[6]<<" ";
	cout<<arr[7]<<" ";
	cout<<arr[8]<<" ";
	cout<<arr[9]<<" ";
	cout<<arr[10]<<" ";
	cout<<arr[11]<<" ";
	cout<<arr[12]<<" ";
	cout<<arr[13]<<" ";
	cout<<arr[14]<<endl;
	cout<<"-------------------------------------------------"<<endl;
	cout<<"                    Part B"<<endl;
	cout<<arr[0]<<endl;
	cout<<arr[1]<<endl;
	cout<<arr[2]<<endl;
	cout<<arr[3]<<endl;
	cout<<arr[4]<<endl;
	cout<<arr[5]<<endl;
	cout<<arr[6]<<endl;
	cout<<arr[7]<<endl;
	cout<<arr[8]<<endl;
	cout<<arr[9]<<endl;
	cout<<arr[10]<<endl;
	cout<<arr[11]<<endl;
	cout<<arr[12]<<endl;
	cout<<arr[13]<<endl;
	cout<<arr[14]<<endl;
	cout<<"-------------------------------------------------"<<endl;
	cout<<"                    Part C"<<endl;	
    cout<<arr[0]<<" ";
	cout<<arr[1]<<" ";
	cout<<arr[2]<<" ";
	cout<<arr[3]<<" ";
	cout<<arr[4]<<endl;
	cout<<arr[5]<<" ";
	cout<<arr[6]<<" ";
	cout<<arr[7]<<" ";
	cout<<arr[8]<<" ";
	cout<<arr[9]<<endl;
	cout<<arr[10]<<" ";
	cout<<arr[11]<<" ";
	cout<<arr[12]<<" ";
	cout<<arr[13]<<" ";
	cout<<arr[14]<<endl;
		cout<<"-------------------------------------------------"<<endl;
	cout<<"                    Part D"<<endl;
	cout<<arr[14]<<" ";
	cout<<arr[13]<<" ";
	cout<<arr[12]<<" ";
	cout<<arr[11]<<" ";
	cout<<arr[10]<<" ";
	cout<<arr[9]<< " ";
	cout<<arr[8]<< " ";
	cout<<arr[7]<< " ";
	cout<<arr[6]<< " ";
	cout<<arr[5]<< " ";
	cout<<arr[4]<< " ";
	cout<<arr[3]<< " ";
	cout<<arr[2]<< " ";
	cout<<arr[1]<< " ";
	cout<<arr[0]<< " ";
	return 0;
}
